version: 2

models:
  - name: stg_greenery__addresses
    description: "Detailed address info"
    columns:
      - name: address_id
        description: "The primary key for this table"
  
  - name: stg_greenery__events
    description: "Customers' events info"
    columns:
      - name: event_id
        description: "The primary key for this table"

  - name: stg_greenery__order_items
    description: "Ordered items and quantities associated with an order"
    columns:
      - name: order_id
        description: "The primary key for this table"

  - name: stg_greenery__orders
    description: "Order detailed info, including discounts and shipping"
    columns:
      - name: order_id
        description: "The primary key for this table"

  - name: stg_greenery__products
    description: "Product detailed info, price and avaiablily"
    columns:
      - name: product_id
        description: "The primary key for this table"

  - name: stg_greenery__promos
    description: "Promotion details, validity"
    columns:
      - name: promo_id
        description: "The primary key for this table"

  - name: stg_greenery__users
    description: "User basic info"
    columns:
      - name: user_id
        description: "The primary key for this table"
        